### ISSUE TITLE
DEFAULT_BRAIN_PORT issue unexpected token

### ISSUE THREAD

**Issue by jaburges** [jakeblatchford/neeo-homeassistant#3]
/home/jamie/homeassistant/lib/python3.5/site-packages/NEEO/node_modules/neeo-sdk/lib/device/brain/urlbuilder.js:6
module.exports.buildBrainUrl = function(brain, baseUrl, brainport = DEFAULT_BRAIN_PORT) {
                                                                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jamie/homeassistant/lib/python3.5/site-packages/NEEO/node_modules/neeo-sdk/lib/recipe/index.js:7:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jamie/homeassistant/lib/python3.5/site-packages/NEEO/node_modules/neeo-sdk/lib/index.js:4:17)
    at Module._compile (module.js:409:26)

**Comment by jaburges** [comment]
Ubuntu 16

Needed NodeJS 6.x
